class_assessments/week_7/locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("books/", views.BookListView.as_view(), name="books"),
    path("books/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("authors/", views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(),name='my-borrowed'),
    path('allborrowedbooks/', views.AllBorrowedBooksListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

class_assessments/week_7/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("catalog/", include('catalog.urls')),
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url = 'catalog/', permanent = True)) #Insert URL maps to redirect the base URL to our application
] + [path('accounts/', include('django.contrib.auth.urls')),]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

class_assessments/week_7/locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

# verbose_name - As labels to the field
# help_text - As helpful text to the field so that users can know how to interact with the field.


# Create your models here.
class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text = 'Enter a book genre (e.g Science Fiction)')

    def __str__(self):
        """String for representing the Model object"""
        return self.name


class Language(models.Model):
    """Model representing the language for a book."""
    language_type = models.CharField(max_length=20, help_text="Enter your language of the book you want(e.g English, Farsi)")

    def __str__(self) -> str:
        return self.language_type


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign key used because book can only have one author but authors
    # can have many books (One to Many)
    # Authors as a string rather than an object because it hasn't been
    # declared yet in the file.

    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField("ISBN", max_length=13, unique=True, help_text="13 characters <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number</a>",)

    # ManyToManyField used because genre can contain many books.
    # Books can cover many genres.
    # Genre class has already defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    
    def display_genre(self):
        """Create a string for the genre. This is required to display the genre in Admin."""
        return ','.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'
    
    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse("book-detail", args=[str(self.id)])  #type: ignore

    def __str__(self) -> str:
        return self.title


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")

    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    language = models.ManyToManyField(Language, help_text="Select your language for this book")

    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reversed'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned',"Set book as returned"),)

    def __str__(self) -> str:
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)


class Author(models.Model):
    """Model representing an author"""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died',null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']


    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse("author-detail", args=[str(self.id)])        #type:ignore

    def __str__(self) -> str:
        """String for representing the model object."""
        return f'{self.last_name}, {self.first_name}'

class_assessments/week_7/locallibrary/catalog/forms.py
import datetime
from attr import fields

from django import forms

from django.forms import ModelForm

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from catalog.models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


class RenewBookModelForm(ModelForm):

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in the past'))

        # Check if the date is in the allowed range(+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always to return the cleaned data
        return data


    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_text = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

class_assessments/week_7/locallibrary/catalog/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.http import Http404
from django.contrib.auth.decorators import login_required, permission_required
from .models import Book, Author, BookInstance, Genre
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import CreateView,UpdateView,DeleteView

from catalog.forms import RenewBookForm
from catalog.models import Author
# Create your views here.


"""
from django.contrib.auth.decorators import permission_required

@permission_required('catalog.can_mark_returned')
@permission_required('catalog.can_edit')
For functions-based views


from django.contrib.auth.mixins import PermissionRequiredMixin

class MyView(PermissionRequiredMixin, View):
    permission_required = 'catalog.can_mark_returned'
    
    # or for multiple permissions
    permission_required = ('catalog.can_mark_returned','catalog.can_edit',)


"""
@login_required
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact = 'a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Count of genres
    num_genres = Genre.objects.count()

    # Count of books that contain a particular word(case insensitive)
    num_particular_books = Book.objects.filter(title__icontains="wind").count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_particular_books': num_particular_books,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'catalog/index.html', context=context)


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 2
    context_object_name = 'book_list'
    # your own name for the list as a template variable.

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['some_data'] = 'This is just some data'
        return context

    queryset = Book.objects.filter(title__icontains = 'a')[:5]
    # Get me five books that contain 'a'.
    def get_queryset(self):
        return self.queryset

    template_name = 'books/book_list.html'
    # Specify your own template name/location


class BookDetailView(LoginRequiredMixin, generic.DetailView):       # Use this or...
    model = Book
    login_url = '/login/'
    redirect_field_name = 'redirect_to'


@login_required
def book_detail_view(request, primary_key):     # Use this
    try:
        book = Book.objects.get(id=primary_key)
    except Book.DoesNotExist:
        raise Http404('Book does not exist!')

    return render(request, 'catalog/book_detail.html', context={'book': book})


class AuthorListView(LoginRequiredMixin,generic.ListView):
    model = Author
    context_object_name = 'author_list'
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    
    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        context['some_data'] = "This is just some data"
        return context
    
    def get_queryset(self):
        return Author.objects.filter(last_name__startswith = 'A')

    template_name = 'authors/author_list.html'


class AuthorDetailView(LoginRequiredMixin,generic.DetailView):
    model = Author
    login_url = '/login/'
    redirect_field_name = 'redirect_to'



@login_required
def author_detail_view(request, primary_key):
    try:
        author = Author.objects.get(pk=primary_key)
    except Author.DoesNotExist:
        raise Http404('Author does not exist!')

    return render(request, 'catalog/author_detail.html', context={'author': author})


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 2

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def all_borrowed_book_list_view(request, primary_key):
    try:
        all_borrowed_book = BookInstance.objects.filter(status__exact='o')
    except BookInstance.DoesNotExist:
        raise Http404('No borrowed books!')
    
    return render(request,'catalog/bookinstance_list_all-borrowed.html', context={'all-borrowed-book':all_borrowed_book})

class AllBorrowedBooksListView(PermissionRequiredMixin,generic.ListView):
    """Generic class-based view listin all borrowed books to the librarian"""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_all_borrowed.html'
    paginate_by = 2
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.all().filter(status__exact='o').order_by('due_back')
    


@login_required
@permission_required('catalog.can_mark_returned',raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid
        if form.is_valid():
            # process the data in form.cleaned_data as required(here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If this is a GET (or any method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date':proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


# To delete, create and update Authors
class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']
    initial = {'date_of_death': '11/06/2020'}


class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__' # Not recommended (potential security issue if more fields added)


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

class_assessments/week_7/locallibrary/catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html' %}


{% block content %}
<h1>Author: {{ author.last_name }} {{ author.first_name }}</h1>

<p>List of books written:</p>

<ul>
    {% for book in author.book_set.all %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
    {% endfor %}
</ul>


{% endblock %}

class_assessments/week_7/locallibrary/catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>List of all Authors</h1>
    {% if author_list %}
    <ul>
        {% for author in author_list %}
        <li><a href={{ author.get_absolute_url }}>{{ author.first_name }}, {{ author.last_name }}</a></li>
        {% endfor %}

    </ul>

    {% endif %}

{% endblock %}

class_assessments/week_7/locallibrary/catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

class_assessments/week_7/locallibrary/catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>List of all Books</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href= "{{ book.get_absolute_url }}">{{ book.title }}</a>
                    ({{ book.author }})
                </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

class_assessments/week_7/locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Renew: {{ book_instance.book.title }}</h1>
<p>Borrower: {{ book_instance.borrower }}</p>
<p {% if book_instance.is_overdue %}class="text-danger"{% endif %}>
    Due date: {{ book_instance.due_back }}
</p>

<form action='' method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

{% endblock %}

class_assessments/week_7/locallibrary/catalog/templates/catalog/bookinstance_list_all_borrowed.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>All Borrowed Books</h1>

<ul>

    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
        ({{ bookinst.due_back }}) - {{ user.get_username }}
        {% if perms.catalog.can_mark_returned %} -
        <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
        {% endif %}
    </li>
    {% endfor %}

</ul>

{% endblock %}

class_assessments/week_7/locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Borrowed Books</h1>

{% if bookinstance_list %}
<ul>
    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>({{ bookinst.due_back }})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no books borrowed.</p>
{% endif %}
{% endblock %}

class_assessments/week_7/locallibrary/catalog/templates/catalog/index.html
{% extends "base_generic.html" %}
<head>
  {% block title %}<title>Awwal's Local Library</title>{% endblock %}
</head>

{% block content %}
  <h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Genres:</strong> {{ num_genres }}</li>
    <li><strong>Books that contains Letter 'wind'</strong> {{ num_particular_books }}</li>

    <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>

    
  </ul>
{% endblock %}